[2019-07-04 11:15:12,588][MainThread:256][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:16:16,358][Thread-5:14524][task_id:backend.views][views.py:256][INFO][[{'sid': 46, 'lnglat': [-119.9, 0.13601]}, {'sid': 17, 'lnglat': [-119.856, 0.152649]}, {'sid': 10, 'lnglat': [-119.851, 0.152581]}, {'sid': 30, 'lnglat': [-119.732, 0.082913]}, {'sid': 16, 'lnglat': [-119.92, 0.156511]}, {'sid': 44, 'lnglat': [-119.921, 0.158505]}, {'sid': 3, 'lnglat': [-119.908, 0.192592]}, {'sid': 13, 'lnglat': [-119.84, 0.14616]}, {'sid': 43, 'lnglat': [-119.843, 0.148224]}, {'sid': 10, 'lnglat': [-119.845, 0.147416]}, {'sid': 38, 'lnglat': [-119.967, 0.168465]}, {'sid': 26, 'lnglat': [-119.728, 0.056713]}, {'sid': 8, 'lnglat': [-119.863, 0.15316]}, {'sid': 40, 'lnglat': [-119.869, 0.153028]}, {'sid': 32, 'lnglat': [-119.769, 0.124401]}, {'sid': 1, 'lnglat': [-119.863, 0.145411]}, {'sid': 19, 'lnglat': [-119.849, 0.12557]}, {'sid': 41, 'lnglat': [-119.848, 0.118727]}, {'sid': 49, 'lnglat': [-119.862, 0.16836]}, {'sid': 24, 'lnglat': [-119.862, 0.122994]}, {'sid': 41, 'lnglat': [-119.86, 0.12499]}, {'sid': 9, 'lnglat': [-119.943, 0.156403]}, {'sid': 47, 'lnglat': [-119.949, 0.150787]}, {'sid': 44, 'lnglat': [-119.941, 0.15718]}, {'sid': 45, 'lnglat': [-119.806, 0.038473]}, {'sid': 25, 'lnglat': [-119.827, 0.0348]}, {'sid': 4, 'lnglat': [-119.872, 0.11194]}, {'sid': 31, 'lnglat': [-119.872, 0.112024]}, {'sid': 42, 'lnglat': [-119.819, 0.121702]}, {'sid': 47, 'lnglat': [-119.778, 0.048302]}, {'sid': 28, 'lnglat': [-119.779, 0.041761]}, {'sid': 27, 'lnglat': [-119.806, 0.017157]}, {'sid': 14, 'lnglat': [-119.814, 0.10334]}, {'sid': 34, 'lnglat': [-119.836, 0.135577]}, {'sid': 50, 'lnglat': [-119.904, 0.18622]}, {'sid': 7, 'lnglat': [-119.905, 0.178729]}, {'sid': 2, 'lnglat': [-119.883, 0.125398]}, {'sid': 41, 'lnglat': [-119.881, 0.12499]}, {'sid': 37, 'lnglat': [-119.897, 0.153395]}, {'sid': 33, 'lnglat': [-119.891, 0.153321]}, {'sid': 44, 'lnglat': [-119.959, 0.158774]}, {'sid': 11, 'lnglat': [-119.883, 0.147162]}, {'sid': 5, 'lnglat': [-119.884, 0.138698]}, {'sid': 35, 'lnglat': [-119.89, 0.112133]}, {'sid': 20, 'lnglat': [-119.771, 0.03345]}, {'sid': 21, 'lnglat': [-119.856, 0.166605]}, {'sid': 10, 'lnglat': [-119.855, 0.158738]}, {'sid': 7, 'lnglat': [-119.85, 0.18067]}, {'sid': 49, 'lnglat': [-119.84, 0.18792]}, {'sid': 5, 'lnglat': [-119.869, 0.188921]}, {'sid': 6, 'lnglat': [-119.855, 0.201428]}, {'sid': 10, 'lnglat': [-119.855, 0.199038]}, {'sid': 15, 'lnglat': [-119.83, 0.140016]}, {'sid': 13, 'lnglat': [-119.83, 0.140151]}, {'sid': 36, 'lnglat': [-119.911, 0.119243]}, {'sid': 39, 'lnglat': [-119.88, 0.125653]}, {'sid': 41, 'lnglat': [-119.87, 0.12499]}, {'sid': 22, 'lnglat': [-119.764, 0.048301]}, {'sid': 10, 'lnglat': [-119.87, 0.218665]}, {'sid': 12, 'lnglat': [-119.916, 0.174077]}, {'sid': 23, 'lnglat': [-119.738, 0.04669]}, {'sid': 47, 'lnglat': [-119.779, 0.054504]}, {'sid': 22, 'lnglat': [-119.771, 0.058487]}, {'sid': 47, 'lnglat': [-119.789, 0.05481]}, {'sid': 47, 'lnglat': [-119.799, 0.05481]}, {'sid': 47, 'lnglat': [-119.809, 0.0551]}, {'sid': 45, 'lnglat': [-119.806, 0.05845]}, {'sid': 47, 'lnglat': [-119.82, 0.0551]}, {'sid': 47, 'lnglat': [-119.829, 0.0551]}, {'sid': 47, 'lnglat': [-119.839, 0.0551]}, {'sid': 47, 'lnglat': [-119.85, 0.0551]}, {'sid': 47, 'lnglat': [-119.859, 0.0551]}, {'sid': 47, 'lnglat': [-119.869, 0.057031]}, {'sid': 47, 'lnglat': [-119.872, 0.058558]}, {'sid': 47, 'lnglat': [-119.87, 0.068313]}, {'sid': 47, 'lnglat': [-119.869, 0.067734]}, {'sid': 47, 'lnglat': [-119.87, 0.078482]}, {'sid': 47, 'lnglat': [-119.873, 0.088408]}, {'sid': 47, 'lnglat': [-119.88, 0.0899]}, {'sid': 47, 'lnglat': [-119.889, 0.0899]}, {'sid': 47, 'lnglat': [-119.899, 0.094487]}, {'sid': 47, 'lnglat': [-119.908, 0.098571]}, {'sid': 47, 'lnglat': [-119.91, 0.101421]}, {'sid': 47, 'lnglat': [-119.912, 0.108348]}, {'sid': 47, 'lnglat': [-119.919, 0.11484]}, {'sid': 47, 'lnglat': [-119.927, 0.118486]}, {'sid': 10, 'lnglat': [-119.87, 0.218401]}, {'sid': 10, 'lnglat': [-119.86, 0.21402]}, {'sid': 47, 'lnglat': [-119.929, 0.121107]}, {'sid': 47, 'lnglat': [-119.932, 0.128336]}, {'sid': 10, 'lnglat': [-119.854, 0.208638]}, {'sid': 47, 'lnglat': [-119.932, 0.138533]}, {'sid': 47, 'lnglat': [-119.932, 0.148353]}, {'sid': 10, 'lnglat': [-119.855, 0.188612]}, {'sid': 47, 'lnglat': [-119.94, 0.14964]}, {'sid': 44, 'lnglat': [-119.93, 0.15718]}, {'sid': 10, 'lnglat': [-119.855, 0.178754]}, {'sid': 49, 'lnglat': [-119.851, 0.18038]}, {'sid': 7, 'lnglat': [-119.859, 0.18067]}, {'sid': 10, 'lnglat': [-119.855, 0.168632]}, {'sid': 49, 'lnglat': [-119.855, 0.178532]}, {'sid': 47, 'lnglat': [-119.96, 0.151115]}, {'sid': 44, 'lnglat': [-119.95, 0.15718]}, {'sid': 10, 'lnglat': [-119.846, 0.148905]}, {'sid': 13, 'lnglat': [-119.827, 0.138701]}, {'sid': 13, 'lnglat': [-119.821, 0.135801]}, {'sid': 13, 'lnglat': [-119.81, 0.13572]}, {'sid': 32, 'lnglat': [-119.819, 0.137635]}, {'sid': 22, 'lnglat': [-119.769, 0.054376]}, {'sid': 13, 'lnglat': [-119.8, 0.13572]}, {'sid': 32, 'lnglat': [-119.809, 0.13514]}, {'sid': 22, 'lnglat': [-119.771, 0.068298]}, {'sid': 13, 'lnglat': [-119.79, 0.13572]}, {'sid': 22, 'lnglat': [-119.793, 0.13685]}, {'sid': 32, 'lnglat': [-119.799, 0.13514]}, {'sid': 22, 'lnglat': [-119.771, 0.078499]}, {'sid': 13, 'lnglat': [-119.78, 0.13572]}, {'sid': 22, 'lnglat': [-119.771, 0.088333]}, {'sid': 13, 'lnglat': [-119.779, 0.136742]}, {'sid': 22, 'lnglat': [-119.771, 0.098466]}, {'sid': 22, 'lnglat': [-119.771, 0.108342]}, {'sid': 22, 'lnglat': [-119.772, 0.118502]}, {'sid': 22, 'lnglat': [-119.779, 0.12441]}, {'sid': 32, 'lnglat': [-119.779, 0.12441]}, {'sid': 22, 'lnglat': [-119.789, 0.12557]}, {'sid': 32, 'lnglat': [-119.789, 0.124934]}, {'sid': 22, 'lnglat': [-119.792, 0.128363]}, {'sid': 32, 'lnglat': [-119.794, 0.128342]}, {'sid': 5, 'lnglat': [-119.869, 0.187634]}, {'sid': 7, 'lnglat': [-119.869, 0.18067]}, {'sid': 5, 'lnglat': [-119.876, 0.178743]}, {'sid': 7, 'lnglat': [-119.88, 0.18067]}, {'sid': 5, 'lnglat': [-119.876, 0.168626]}, {'sid': 49, 'lnglat': [-119.86, 0.17342]}, {'sid': 5, 'lnglat': [-119.876, 0.15876]}, {'sid': 5, 'lnglat': [-119.88, 0.152557]}, {'sid': 5, 'lnglat': [-119.884, 0.148588]}, {'sid': 41, 'lnglat': [-119.851, 0.12499]}, {'sid': 49, 'lnglat': [-119.838, 0.188362]}, {'sid': 49, 'lnglat': [-119.834, 0.198511]}, {'sid': 5, 'lnglat': [-119.889, 0.13601]}, {'sid': 7, 'lnglat': [-119.889, 0.18067]}, {'sid': 41, 'lnglat': [-119.84, 0.11223]}, {'sid': 45, 'lnglat': [-119.806, 0.048314]}, {'sid': 28, 'lnglat': [-119.804, 0.040736]}, {'sid': 5, 'lnglat': [-119.896, 0.136249]}, {'sid': 49, 'lnglat': [-119.83, 0.199629]}, {'sid': 28, 'lnglat': [-119.789, 0.04176]}, {'sid': 7, 'lnglat': [-119.899, 0.18067]}, {'sid': 44, 'lnglat': [-119.92, 0.159942]}, {'sid': 44, 'lnglat': [-119.911, 0.16008]}, {'sid': 49, 'lnglat': [-119.821, 0.202118]}, {'sid': 41, 'lnglat': [-119.83, 0.11194]}, {'sid': 49, 'lnglat': [-119.825, 0.19855]}, {'sid': 28, 'lnglat': [-119.799, 0.04176]}, {'sid': 44, 'lnglat': [-119.9, 0.16008]}, {'sid': 45, 'lnglat': [-119.809, 0.06264]}, {'sid': 41, 'lnglat': [-119.822, 0.11194]}, {'sid': 49, 'lnglat': [-119.817, 0.204644]}, {'sid': 7, 'lnglat': [-119.907, 0.17429]}, {'sid': 45, 'lnglat': [-119.812, 0.06264]}]]
[2019-07-04 11:17:05,338][MainThread:256][task_id:django.utils.autoreload][autoreload.py:203][INFO][Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 11:17:06,213][MainThread:5540][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:17:15,806][MainThread:5540][task_id:django.utils.autoreload][autoreload.py:203][INFO][Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 11:17:16,712][MainThread:15428][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:18:44,646][MainThread:15428][task_id:django.utils.autoreload][autoreload.py:203][INFO][Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 11:18:45,562][MainThread:13464][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:19:05,395][MainThread:13464][task_id:django.utils.autoreload][autoreload.py:203][INFO][Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 11:19:06,294][MainThread:15556][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:19:12,476][MainThread:15556][task_id:django.utils.autoreload][autoreload.py:203][INFO][Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 11:19:13,374][MainThread:9836][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:19:44,550][MainThread:9836][task_id:django.utils.autoreload][autoreload.py:203][INFO][Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 11:19:45,360][MainThread:6568][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 11:28:46,520][Thread-10:6056][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 226, in calCluster
    [a, b] = mn.shape
ValueError: not enough values to unpack (expected 2, got 1)
[2019-07-04 12:41:18,619][Thread-36:7740][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calTimeSeries/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 106, in calTimeSeries
    params = json.loads(request.body)
  File "D:\Anaconda3\envs\django\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\django\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\envs\django\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2019-07-04 12:59:09,142][Thread-51:10804][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calTimeSeries/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 106, in calTimeSeries
    params = json.loads(request.body)
  File "D:\Anaconda3\envs\django\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\django\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\envs\django\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2019-07-04 13:01:14,403][Thread-51:10804][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 226, in calCluster
    [a, b] = mn.shape
ValueError: not enough values to unpack (expected 2, got 1)
[2019-07-04 13:01:42,349][Thread-54:6480][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 226, in calCluster
    [a, b] = mn.shape
ValueError: not enough values to unpack (expected 2, got 1)
[2019-07-04 13:01:46,929][Thread-48:9480][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 226, in calCluster
    [a, b] = mn.shape
ValueError: not enough values to unpack (expected 2, got 1)
[2019-07-04 13:41:22,163][Thread-62:15432][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 229, in calCluster
    result = Dimension_Reduction_PCA(result)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 135, in Dimension_Reduction_PCA
    pca = pca.fit_transform(feature_matrix)
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\decomposition\pca.py", line 360, in fit_transform
    U, S, V = self._fit(X)
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\decomposition\pca.py", line 382, in _fit
    copy=self.copy)
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\utils\validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\utils\validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
[2019-07-04 13:50:56,998][Thread-62:15432][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 229, in calCluster
    result = Dimension_Reduction_PCA(result)
  File "Y:\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 135, in Dimension_Reduction_PCA
    pca = pca.fit_transform(feature_matrix)
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\decomposition\pca.py", line 360, in fit_transform
    U, S, V = self._fit(X)
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\decomposition\pca.py", line 382, in _fit
    copy=self.copy)
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\utils\validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "D:\Anaconda3\envs\django\lib\site-packages\sklearn\utils\validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
[2019-07-04 19:39:16,810][MainThread:8544][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 19:58:56,239][MainThread:8544][task_id:django.utils.autoreload][autoreload.py:203][INFO][D:\Workspace\Projects\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 19:58:57,672][MainThread:21988][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 21:26:47,322][Thread-40:11360][task_id:django.request][log.py:228][ERROR][Internal Server Error: /calSensorClusters/]
Traceback (most recent call last):
  File "C:\Softwares\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Softwares\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Softwares\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Workspace\Projects\vast-challenge-2019-MC2\RadiationVis\backend\views.py", line 101, in calSensorClusters
    data = calCluster(params['begintime'], params['endtime'])
  File "D:\Workspace\Projects\vast-challenge-2019-MC2\RadiationVis\backend\dataprocessing\cluster.py", line 226, in calCluster
    [a, b] = mn.shape
ValueError: not enough values to unpack (expected 2, got 1)
[2019-07-04 23:06:17,939][MainThread:21988][task_id:django.utils.autoreload][autoreload.py:203][INFO][D:\Workspace\Projects\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 23:06:23,293][MainThread:18884][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-07-04 23:09:37,020][MainThread:18884][task_id:django.utils.autoreload][autoreload.py:203][INFO][D:\Workspace\Projects\vast-challenge-2019-MC2\RadiationVis\backend\views.py changed, reloading.]
[2019-07-04 23:09:41,631][MainThread:3932][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
